import * as vscode from 'vscode';

export interface SceneObject {
  id: string;
  type: string;
  label: string;
  parent: string | null;
  visible: boolean;
  /** Set on a copy made by a duplicate event, naming the object it came
   *  from. Generated objects have no document entry to edit, so the tree
   *  shows them and stops there. */
  derived?: string;
}

// Wireframe SVGs in media/icons, one per magpylib class, colored by
// category (magnets red, currents blue, sensors green, misc gray).
const TYPE_ICON_FILES: Record<string, string> = {
  'magnet.Cuboid': 'cuboid',
  'magnet.Cylinder': 'cylinder',
  'magnet.CylinderSegment': 'cylinder-segment',
  'magnet.Sphere': 'sphere',
  'magnet.Tetrahedron': 'tetrahedron',
  'magnet.TriangularMesh': 'mesh',
  'current.Circle': 'loop',
  'current.Polyline': 'polyline',
  'misc.Dipole': 'dipole',
  'misc.CustomSource': 'custom',
  Sensor: 'sensor',
};

function iconFor(
  type: string,
  extensionUri: vscode.Uri,
): vscode.Uri | vscode.ThemeIcon {
  if (type === 'Collection') {
    return new vscode.ThemeIcon('folder');
  }
  const file =
    TYPE_ICON_FILES[type] ?? (type.startsWith('magnet.') ? 'cuboid' : 'custom');
  return vscode.Uri.joinPath(extensionUri, 'media', 'icons', `${file}.svg`);
}

const TREE_MIME = 'application/vnd.code.tree.magpylib-studio.sceneview';

/**
 * Sidebar scene outline. The engine reports a flat list with `parent` ids
 * (depth-first); the root call fetches and caches it, child calls slice it.
 * Drag & drop reparents: onto a Collection = move in, onto a plain object =
 * move next to it, onto empty space = move to the scene root.
 */
export class SceneTreeProvider
  implements
    vscode.TreeDataProvider<SceneObject>,
    vscode.TreeDragAndDropController<SceneObject>
{
  private emitter = new vscode.EventEmitter<void>();
  readonly onDidChangeTreeData = this.emitter.event;
  readonly dragMimeTypes = [TREE_MIME];
  readonly dropMimeTypes = [TREE_MIME];
  private objects: SceneObject[] = [];

  constructor(
    private readonly extensionUri: vscode.Uri,
    private readonly listObjects: () => Promise<SceneObject[]>,
    private readonly moveObject: (id: string, parent: string | null) => Promise<void>,
  ) {}

  refresh(): void {
    this.emitter.fire();
  }

  getTreeItem(obj: SceneObject): vscode.TreeItem {
    const hasChildren = this.objects.some((o) => o.parent === obj.id);
    const item = new vscode.TreeItem(
      obj.label,
      hasChildren
        ? vscode.TreeItemCollapsibleState.Expanded
        : vscode.TreeItemCollapsibleState.None,
    );
    item.id = obj.id;
    if (obj.derived) {
      // A generated copy: real geometry, real field source, but no spec —
      // every edit command would fail on it, so it gets no context value
      // (nothing in the menus matches), no selection, and a dimmed icon.
      item.description = `${obj.type} · copy of ${obj.derived}`;
      item.tooltip =
        `${obj.id} — generated by the duplicate event on ${obj.derived}. ` +
        `Edit the event or its variables, not the copy.`;
      // deliberately outside the magpy* namespace: every scene-view menu
      // entry is gated on /^magpy/, so this matches none of them
      item.contextValue = 'derivedCopy';
      item.iconPath = new vscode.ThemeIcon(
        'circle-small-filled',
        new vscode.ThemeColor('disabledForeground'),
      );
      return item;
    }
    item.description = obj.visible ? obj.type : `${obj.type} · hidden`;
    item.tooltip = `${obj.id} — ${obj.type}${obj.visible ? '' : ' (hidden)'}`;
    // visibility is part of contextValue so the inline eye can flip its icon
    item.contextValue =
      (obj.type === 'Collection' ? 'magpyCollection' : 'magpyObject') +
      (obj.visible ? 'Visible' : 'Hidden');
    item.iconPath = obj.visible
      ? iconFor(obj.type, this.extensionUri)
      : new vscode.ThemeIcon('eye-closed', new vscode.ThemeColor('disabledForeground'));
    item.command = {
      command: 'magpylib-studio.selectObject',
      title: 'Select in Studio',
      arguments: [obj.id],
    };
    return item;
  }

  async getChildren(element?: SceneObject): Promise<SceneObject[]> {
    if (!element) {
      this.objects = await this.listObjects();
      return this.objects.filter((o) => o.parent === null);
    }
    return this.objects.filter((o) => o.parent === element.id);
  }

  handleDrag(source: readonly SceneObject[], dataTransfer: vscode.DataTransfer): void {
    // generated copies cannot be reparented: they are not in the document
    const movable = source.filter((o) => !o.derived);
    if (movable.length) {
      dataTransfer.set(TREE_MIME, new vscode.DataTransferItem(movable));
    }
  }

  async handleDrop(
    target: SceneObject | undefined,
    dataTransfer: vscode.DataTransfer,
  ): Promise<void> {
    const source = dataTransfer.get(TREE_MIME)?.value as SceneObject[] | undefined;
    if (!source?.length) {
      return;
    }
    const parent =
      target === undefined
        ? null
        : target.type === 'Collection' && !target.derived
          ? target.id
          : target.parent;
    for (const obj of source) {
      if (obj.id !== parent && (obj.parent ?? null) !== parent) {
        await this.moveObject(obj.id, parent); // engine rejects cycles cleanly
      }
    }
  }
}
